sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
after_success: 'npm run coveralls'
cache:
  directories:
    - "node_modules"

