sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
after_script:
- npm run report-coverage
cache:
  directories:
    - "node_modules"

