sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
before_script:
  - npm install -g gulp-cli
script:
  - npm test
  - gulp
cache:
  directories:
    - "node_modules"

